// When the document is ready
$(document).ready(function() {

  // When the hamburger is clicked
  $( "#menu-toggle" ).bind("click keypress", (e) => {
    if (e.type != "keypress" || e.keyCode == 13) {
      // If menu is hidden
      if ( $( "#main-menu" ).is( ":hidden" ) ) {
        // Slide it down
        $( "#main-menu" ).slideDown({
          start: function () {
            $(this).css({
              display: "flex",
              duration: "slow"
            })
          }
        });
      } 
      else {
        // And if it isn't
        $( "#main-menu" ).slideUp( "slow" );
      }
    }
  });

  // Dropdowns
  //
  // I've hard-coded closing of the other dropdown.
  // Might expand this to work generally in the future.

  $( "#oblig2" ).bind("click keypress", (e) => {

    if (e.type != "keypress" || e.keyCode == 13) {

      if( $( "#oblig2-content" ).is( ":hidden" ) ) {

        if(! $( "#oblig3-content" ).is( ":hidden" ) ){
          $( "#oblig3-content" ).slideUp( "fast" );
        }

        if(! $( "#oblig4-content" ).is( ":hidden" ) ){
          $( "#oblig4-content" ).slideUp( "fast" );
        }

        if(! $( "#oblig5-content" ).is( ":hidden" ) ){
          $( "#oblig5-content" ).slideUp( "fast" );
        }

        $( "#oblig2-content" ).slideDown({
          start: function () {
            $(this).css({
              display: "flex",
              duration: "slow"
            })
          }
        });

      }

      else {
        $( "#oblig2-content" ).slideUp( "slow");
      }

    }
  });

  $( "#oblig3" ).bind("click keypress", (e) => {

    if (e.type != "keypress" || e.keyCode == 13) {

      if( $( "#oblig3-content" ).is( ":hidden" ) ) {

        if(! $( "#oblig2-content" ).is( ":hidden" ) ){
          $( "#oblig2-content" ).slideUp( "fast" );
        }

        if(! $( "#oblig4-content" ).is( ":hidden" ) ){
          $( "#oblig4-content" ).slideUp( "fast" );
        }

        if(! $( "#oblig5-content" ).is( ":hidden" ) ){
          $( "#oblig5-content" ).slideUp( "fast" );
        }

        $( "#oblig3-content" ).slideDown({
          start: function () {
            $(this).css({
              display: "flex",
              duration: "slow"
            })
          }

        });
      }

      else {
        $( "#oblig3-content" ).slideUp( "slow" );
      }

    }
  });

  $( "#oblig4" ).bind("click keypress", (e) => {

    if (e.type != "keypress" || e.keyCode == 13) {

      if( $( "#oblig4-content" ).is( ":hidden" ) ) {

        if(! $( "#oblig2-content" ).is( ":hidden" ) ){
          $( "#oblig2-content" ).slideUp( "fast" );
        }

        if(! $( "#oblig3-content" ).is( ":hidden" ) ){
          $( "#oblig3-content" ).slideUp( "fast" );
        }

        if(! $( "#oblig5-content" ).is( ":hidden" ) ){
          $( "#oblig5-content" ).slideUp( "fast" );
        }

        $( "#oblig4-content" ).slideDown({
          start: function () {
            $(this).css({
              display: "flex",
              duration: "slow"
            })
          }
        });
      }

      else {
        $( "#oblig4-content" ).slideUp( "slow" );
      }

    }
  });

  $( "#oblig5" ).bind("click keypress", (e) => {

    if (e.type != "keypress" || e.keyCode == 13) {

      if( $( "#oblig5-content" ).is( ":hidden" ) ) {

        if(! $( "#oblig2-content" ).is( ":hidden" ) ){
          $( "#oblig2-content" ).slideUp( "fast" );
        }

        if(! $( "#oblig3-content" ).is( ":hidden" ) ){
          $( "#oblig3-content" ).slideUp( "fast" );
        }

        if(! $( "#oblig4-content" ).is( ":hidden" ) ){
          $( "#oblig4-content" ).slideUp( "fast" );
        }

        $( "#oblig5-content" ).slideDown({
          start: function () {
            $(this).css({
              display: "flex",
              duration: "slow"
            })
          }
        });
      }

      else {
        $( "#oblig5-content" ).slideUp( "slow" );
      }

    }

  });

  // Wrote this to replace setting them manually, but will have to revert back.
  // Using bind() to add functionality doesn't work with $(this). So I will either
  // have to spend some time experimenting, or get on with the actual assignment.
  // Doing it manually is a lot quicker in this situation, but would love to come back and fix it.
  /* $('.dropdown').click(function () {
    let index = $(this).index() - 1,
        newTarget = $('.dropdown-content').eq(index).slideDown();
        
    $('.dropdown-content').not(newTarget).slideUp();
  }); */

  // Quickfix for a problem combining Flex and jQuery
  // BUG: Inline JS generated by jQuery sets the menu visible when resizing back and forth through phone and tablet mode.
  // Will however work normally if used as intended.
  $(window).resize(() => {
    if($(window).width() > 650 && $( "#main-menu" ).is(":hidden")) {
      $( "#main-menu" ).show();
    }
  });

  // GIF Hovers
  $( ".gif-exists" ).each((e, x) => {
    let src = $(x).attr('src');

    $(x).hover(function() {
      $(x).attr('src', src.replace('.png', '-anim.gif'));
    }, function(){
      $(x).attr('src', src);
    });
  });

});